nav:
    - Kleio source files:
        - Kleio notation:
            - kleio_file_structure.md
            - kleio_notation_reference.md
            - linked_data_providers.md

        -  Kleio schemas:
            - kleio_schema_files_location.md
            - kleio_source_model_diagram.md

        - Kleio source to database mapping:
            - source_db_overview.md
            - source_db_mapping_syntax.md
            - source_db_mappings_semantics.md

        - Special source types:
            - identification_lists.md

    - Database:
        - processing_new_versions_of_sources.md

    - Directories and files:
        - web_timelink_home_layout.md
